### ISSUE TITLE
Version 1.6.6 = 1.6.7

### ISSUE THREAD

**Issue by remicollet** [tecnickcom/tc-lib-unicode-data#3]
Version 1.6.7 have same commit reference than 1.6.6...

VERSION file is not updated
composer.json is not updated like other components to allow phpunit7

Something missing ?

**Comment by remicollet** [comment]
BTW, I don't see real value to tag a new version for such changes... code is the same...

**Comment by nicolaasuni** [comment]
Thanks for pointing this out.
It has happened because of a bulk update.
